
package co.com.mauricio.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FrontService", targetNamespace = "http://servicio.pruebas.tecnocom.com/")
public interface FrontService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://servicio.pruebas.tecnocom.com/", className = "co.com.mauricio.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://servicio.pruebas.tecnocom.com/", className = "co.com.mauricio.client.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod(operationName = "Hello")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://servicio.pruebas.tecnocom.com/", className = "co.com.mauricio.client.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://servicio.pruebas.tecnocom.com/", className = "co.com.mauricio.client.HelloResponse")
    public void hello();

}
