
package co.com.mauricio.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "FrontServiceService", targetNamespace = "http://servicio.pruebas.tecnocom.com/", wsdlLocation = "http://10.25.1.37:7001/WS_Prueba-ViewController-context-root/FrontServicePort?WSDL")
public class FrontServiceService
    extends Service
{

    private final static URL FRONTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FRONTSERVICESERVICE_EXCEPTION;
    private final static QName FRONTSERVICESERVICE_QNAME = new QName("http://servicio.pruebas.tecnocom.com/", "FrontServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.25.1.37:7001/WS_Prueba-ViewController-context-root/FrontServicePort?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FRONTSERVICESERVICE_WSDL_LOCATION = url;
        FRONTSERVICESERVICE_EXCEPTION = e;
    }

    public FrontServiceService() {
        super(__getWsdlLocation(), FRONTSERVICESERVICE_QNAME);
    }

    public FrontServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns FrontService
     */
    @WebEndpoint(name = "FrontServicePort")
    public FrontService getFrontServicePort() {
        return super.getPort(new QName("http://servicio.pruebas.tecnocom.com/", "FrontServicePort"), FrontService.class);
    }

    private static URL __getWsdlLocation() {
        if (FRONTSERVICESERVICE_EXCEPTION!= null) {
            throw FRONTSERVICESERVICE_EXCEPTION;
        }
        return FRONTSERVICESERVICE_WSDL_LOCATION;
    }

}
